id = "of_wisdom"
name = "of Wisdom"
description = "Grants insight."
type = "suffix"
stat = "wisdom"
amount = "1"
quality_min = "common"
slot = ["head", "neck", "torso"]

# level_requirement = 1
# quality_max = "legendary"
