id = "goblin_skull"
name = "goblin skull"
description = "A goblin skull"
item_type = "misc"
subtype = "trash"
rarity = "common"
level_requirement = 1
weight = 1.0
value = 0
flags = []
allowed_classes = []
allowed_races = []
allowed_alignments = []
triggers = []
