[package]
name = "oxide-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
oxide-core = { path = "../core" }
oxide-data = { path = "../data" }
tokio = { version = "1", features = ["net", "io-util", "macros", "sync", "time", "rt"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
tracing = "0.1"
fastrand = "2"
axum = { version = "0.7", features = ["macros"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
