id = "human"
name = "Human"
description = "The human race is known for their adaptability and ambition, thriving in all corners of the world."

allowed_classes = ["warrior", "mage"]
racial_abilities = ["adaptability"]

# attributes = { str = 10, dex = 10, int = 10, wis = 10, con = 10, cha = 10 }
# size = "medium"
# speed = 30
# languages = ["common"]
# hometown = "starting_vale"
# traits = { infravision = 0 }
# familiarity = []
# alignment_tendencies = ["lawful_good", "neutral_good", "chaotic_good", "lawful_neutral", "neutral", "chaotic_neutral"]
