id = "orc"
name = "Orc"
description = "Orcs are fierce and warlike humanoids, hardened by a life of conflict in the harsh wilds."
allowed_classes = ["warrior"]
allowed_alignments = ["lawful_evil", "neutral_evil", "chaotic_evil"]
racial_abilities = []

[allowed_genders.male]
subject = "he"
object = "him"
possessive = "his"

[allowed_genders.female]
subject = "she"
object = "her"
possessive = "hers"

# size = "large"
# speed = 30
# languages = ["orcish", "common"]
# hometown = ""
# traits = { infravision = 60 }
# familiarity = []

[attributes]
strength = 12
constitution = 12
intelligence = 8
charisma = 8
